# ── Servidor ──────────────────────────────────────────────
server.port=8080

# ── PostgreSQL ────────────────────────────────────────────
spring.datasource.url=jdbc:postgresql://localhost:5432/CDRetail_IntelligenceViejo2
spring.datasource.username=postgres
spring.datasource.password=1250143656
spring.datasource.driver-class-name=org.postgresql.Driver

# ── JPA / Hibernate ───────────────────────────────────────
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.sql.init.mode=always

# ── Paginación por defecto ────────────────────────────────
spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100

# ── Logging ───────────────────────────────────────────────
logging.level.com.retailmind=INFO
logging.level.org.hibernate.SQL=WARN
logging.file.name=logs/retailmind.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n

# ── ETL Python ────────────────────────────────────────────
etl.python.path=py
etl.scripts.path=C:/Users/ASUS/Documents/UTEQ/6 SEMESTRE/Construccion de software/1M6DatosCS/retailmind

# ── Inicializacion ClickHouse ─────────────────────────────
init.scripts.path=C:/Users/ASUS/Documents/UTEQ/6 SEMESTRE/Construccion de software/1M6DatosCS/retailmind
CH_HOST=172.29.94.38
CH_PORT=8123
CH_DATABASE=retailmind
CH_USER=default
CH_PASSWORD=retailmind2026

# ── ClickHouse Datasource (Analytics) ────────────────────
clickhouse.datasource.url=jdbc:ch://172.29.94.38:8123/retailmind?compress=0
clickhouse.datasource.username=default
clickhouse.datasource.password=retailmind2026
clickhouse.datasource.driver-class-name=com.clickhouse.jdbc.ClickHouseDriver

# ── Multipart upload ──────────────────────────────────────
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# ── JWT ───────────────────────────────────────────────────
jwt.secret=retailmind-secret-key-2024-very-long-secure-string
jwt.expiration=86400000
jwt.refresh-expiration=604800000
