-- ============================================================================
-- 101_fase5_envios.sql — RetailMind · FASE 5: los ENVÍOS de la década
--
--   docker compose exec -T postgres psql -U postgres -d retailmind \
--       -v ON_ERROR_STOP=1 -f - < retailmind/sql/postgres/101_fase5_envios.sql
--
--   Reanudar tras un corte:  ... -v reanudar=1 ...
--   Reversión:               99_revert_fase5.sql  (ensayo con -v ensayo=1)
--
--   OJO: se ejecuta con `-f -`. La carga va en un PROCEDIMIENTO que hace
--   COMMIT, y eso solo es legal si el CALL no viene en una transacción.
--
-- ---------------------------------------------------------------------------
-- QUÉ ARREGLA
-- ---------------------------------------------------------------------------
-- La carga masiva escribió el ciclo de 9 tablas del pedido pero NUNCA creó
-- envíos: `envio` tenía 2.872 filas y terminaba el 2026-07-23. Los tableros
-- T-4 (Operación y Última Milla) y T-5 (Costo de la Operación) se apoyan en
-- `fact_envio`, así que su serie se cortaba en 19 meses mientras el resto de
-- la casa llegaba a 2034 — sin error y sin explicación en pantalla.
--
-- Esta fase NO TOCA STOCK. Los envíos cuelgan de pedidos que ya existen y que
-- ya movieron su kardex; aquí no se escribe ni una fila de
-- `movimiento_inventario` ni de `inventario`.
--
-- ---------------------------------------------------------------------------
-- LA REGLA: QUÉ PEDIDOS LLEVAN ENVÍO — derivada, no inventada
-- ---------------------------------------------------------------------------
-- Medido sobre los 4.083 pedidos originales, cruzando estado y canal:
--
--   por ESTADO          pedidos  con envío        por CANAL   pedidos  con envío
--   entregado             3.592     73,7 %        web           2.082    100,0 %
--   despachado               16    100,0 %        telefono        778    100,0 %
--   no_entregado            122    100,0 %        tienda          981      1,2 %
--   devuelto                111     78,4 %
--   los otros seis            —      0,0 %
--
-- El «73,7 % de los entregados» NO es azar: es que **la compra en tienda se
-- retira en tienda**. Cruzando las dos dimensiones la regla sale limpia:
--
--     lleva envío  ⇔  estado ∈ {entregado, despachado, no_entregado, devuelto}
--                     Y  canal ≠ 'tienda'
--
-- y con ella los 2.860 pedidos web/teléfono de esos estados tienen los 2.860
-- envíos. Los 12 envíos de pedidos 'tienda' que hay en el seed son ruido
-- (1,2 %) y no se reproducen: un patrón del 1 % no es un patrón.
-- Coherente además con el dinero: `pedido.costo_envio = 0` en los 1.030
-- pedidos de tienda, y ninguno trae transportista ni método de envío.
--
-- ---------------------------------------------------------------------------
-- COHERENCIA CON EL ESTADO DEL PEDIDO — también medida
-- ---------------------------------------------------------------------------
--   pedido despachado    → envío en_transito   (16/16)
--   pedido entregado     → envío entregado     (2.647/2.647)
--   pedido no_entregado  → envío devuelto      (121) · en_transito (1)
--   pedido devuelto      → envío entregado     (80)  · en_transito (7)
--
-- Se reproduce el caso dominante de cada estado. Los residuos de un solo
-- dígito no se imitan.
--
-- LAS FECHAS NO SE INVENTAN: SE LEEN DE `historial_estado_pedido`. Cada pedido
-- ya tiene ahí el instante exacto en que pasó por 'despachado' y por
-- 'entregado'. Derivarlas de ahí hace imposible que un envío se despache antes
-- que su pedido o que entregue antes de despachar — la coherencia temporal no
-- se comprueba después, sale por construcción.
--
-- EL COSTO SALE DEL PEDIDO. Medido: 2.871 de los 2.872 envíos cumplen
-- `envio.costo = pedido.costo_envio` (el que falta es legacy). Se copia, con
-- lo que el invariante queda al 100 % en lo nuevo.
--
-- ---------------------------------------------------------------------------
-- TRAMOS RESERVADOS
-- ---------------------------------------------------------------------------
-- IDs — el techo real NO es el `bigint` de PostgreSQL: es el **UInt32** del
-- almacén (4.294.967.295). `fact_envio.envio_id` y `fact_novedad_envio`
-- (`novedad_id`, `envio_id`, `pedido_id`) son UInt32; `seguimiento_envio` y
-- `envio_detalle` no viajan al DWH.
--
--     envio              2.200.000.000   (2,11 M → tope 2.202,2 M)
--     envio_detalle      2.300.000.000
--     seguimiento_envio  2.400.000.000   (6,3 M  → tope 2.406,3 M)
--     novedad_envio      2.500.000.000
--
-- El id más alto queda en ~2.406 M, al **56 %** del techo UInt32.
-- `novedad_envio.id` es GENERATED BY DEFAULT y no necesita OVERRIDING; los
-- otros tres son GENERATED ALWAYS y sí.
--
-- NÚMEROS DE DOCUMENTO — `envio.numero` es UNIQUE, formato `EN-YYYYMMDD-NNNNNN`
-- con SEIS dígitos en el seed (101412..112019). La banda nueva usa **SIETE
-- dígitos desde 5.000.000**, y ninguna cadena de seis puede igualar a una de
-- siete. `numero_guia` (no único) usa la misma secuencia.
-- La Fase 3 aprendió por qué esto no se razona sino que se COMPRUEBA: allí la
-- banda «única por fase» falló porque el número lleva la fecha y las ventanas
-- de documento sobresalen por los bordes (183 choques). Aquí hay un guardia
-- que compara los números generados contra los existentes ANTES de escribir.
--
-- IDEMPOTENTE (ON CONFLICT DO NOTHING) · POR LOTES CON COMMIT
-- ============================================================================
\set ON_ERROR_STOP on
\timing on

\if :{?reanudar}
\else
  \set reanudar 0
\endif
SELECT set_config('retailmind.reanudar', :'reanudar', false);

SET work_mem = '256MB';
SET maintenance_work_mem = '512MB';
SET synchronous_commit = off;

\echo ''
\echo '=== FASE 5 · ENVIOS DE LA DECADA ==========================================='

-- ════════════════════════════════════════════════════════════════════════════
-- 0. AZAR DETERMINISTA · GUARDIA DEL TRAMO
-- ════════════════════════════════════════════════════════════════════════════
CREATE OR REPLACE FUNCTION pg_temp.u(k text, i bigint) RETURNS numeric
LANGUAGE sql IMMUTABLE PARALLEL SAFE AS
$$ SELECT ((('x' || substr(md5('f5' || k || i::text), 1, 7))::bit(28)::int)
           % 1000000)::numeric / 1000000.0 $$;

CREATE TEMP TABLE f5_medicion(paso text, lote int, inicio timestamptz,
                              fin timestamptz, filas bigint);
CREATE OR REPLACE PROCEDURE pg_temp.medir(p text, l int, i timestamptz, f bigint)
LANGUAGE sql AS
$$ INSERT INTO f5_medicion VALUES (p, l, i, clock_timestamp(), f) $$;

DO $guardia$
DECLARE n bigint; sucias text := '';
        v_re int := current_setting('retailmind.reanudar', true)::int;
BEGIN
    SELECT count(*) INTO n FROM envio             WHERE id >= 2200000000;
    IF n > 0 THEN sucias := sucias || format('  envio: %s%s', n, E'\n'); END IF;
    SELECT count(*) INTO n FROM envio_detalle     WHERE id >= 2300000000;
    IF n > 0 THEN sucias := sucias || format('  envio_detalle: %s%s', n, E'\n'); END IF;
    SELECT count(*) INTO n FROM seguimiento_envio WHERE id >= 2400000000;
    IF n > 0 THEN sucias := sucias || format('  seguimiento_envio: %s%s', n, E'\n'); END IF;
    SELECT count(*) INTO n FROM novedad_envio     WHERE id >= 2500000000;
    IF n > 0 THEN sucias := sucias || format('  novedad_envio: %s%s', n, E'\n'); END IF;

    IF sucias <> '' AND v_re = 0 THEN
        RAISE EXCEPTION 'Los tramos de la Fase 5 YA tienen filas. Revierte con '
                        '99_revert_fase5.sql o reanuda con -v reanudar=1:%', E'\n' || sucias;
    ELSIF sucias <> '' THEN
        RAISE NOTICE 'REANUDANDO sobre una carga incompleta:%', E'\n' || sucias;
    ELSE
        RAISE NOTICE 'Guardia OK: los cuatro tramos estan vacios.';
    END IF;
END
$guardia$;

-- ════════════════════════════════════════════════════════════════════════════
-- 1. EL PLAN: un envío por pedido elegible, con sus fechas LEÍDAS del historial
-- ════════════════════════════════════════════════════════════════════════════
CREATE TEMP TABLE f5_env AS
WITH elegible AS (
    SELECT p.id AS pedido_id, p.canal, p.costo_envio, p.transportista_id,
           p.metodo_envio_id, p.direccion_envio_id, p.fecha_pedido,
           ep.codigo AS estado_pedido,
           row_number() OVER (ORDER BY p.id) AS n
    FROM pedido p
    JOIN estado_pedido ep ON ep.id = p.estado_pedido_id
    WHERE p.canal <> 'tienda'
      AND ep.codigo IN ('entregado', 'despachado', 'no_entregado', 'devuelto')
      AND NOT EXISTS (SELECT 1 FROM envio e WHERE e.pedido_id = p.id)
),
-- Las fechas salen de los hitos que el pedido YA tiene. `min` y no `max`
-- porque un pedido puede tener el hito repetido (19 'confirmado', 8 'pagado'
-- y 5 'despachado' duplicados en el seed original).
hitos AS (
    SELECT h.pedido_id,
           min(h.fecha_creacion) FILTER (WHERE ep.codigo = 'despachado') AS f_desp,
           min(h.fecha_creacion) FILTER (WHERE ep.codigo = 'entregado')  AS f_ent
    FROM historial_estado_pedido h
    JOIN estado_pedido ep ON ep.id = h.estado_pedido_id
    WHERE ep.codigo IN ('despachado', 'entregado')
      AND EXISTS (SELECT 1 FROM elegible el WHERE el.pedido_id = h.pedido_id)
    GROUP BY h.pedido_id
),
peso AS (
    SELECT pd.pedido_id, sum(pd.cantidad * COALESCE(pv.peso_kg, 0))::numeric(8,3) AS kg
    FROM pedido_detalle pd
    JOIN producto_variante pv ON pv.id = pd.producto_variante_id
    WHERE EXISTS (SELECT 1 FROM elegible el WHERE el.pedido_id = pd.pedido_id)
    GROUP BY pd.pedido_id
)
SELECT
    2200000000 + e.n              AS id,
    e.n,
    e.pedido_id,
    e.estado_pedido,
    e.costo_envio                 AS costo,
    e.transportista_id,
    e.metodo_envio_id,
    LEAST(COALESCE(pe.kg, 0), 99999.999)::numeric(8,3) AS peso_total_kg,
    -- Estado del envío: el caso dominante medido para cada estado de pedido.
    CASE e.estado_pedido
        WHEN 'despachado'   THEN 'en_transito'
        WHEN 'entregado'    THEN 'entregado'
        WHEN 'no_entregado' THEN 'devuelto'
        WHEN 'devuelto'     THEN 'entregado'
    END                           AS estado,
    -- Despacho: el hito real. Si faltara, se ancla al pedido + la media medida
    -- (1,74 días) para no dejar NULL en un envío que sí salió.
    COALESCE(h.f_desp, e.fecha_pedido + interval '1.74 days') AS fecha_despacho,
    -- Entrega real: solo si el envío acabó entregado.
    CASE WHEN e.estado_pedido IN ('entregado', 'devuelto')
         THEN COALESCE(h.f_ent, COALESCE(h.f_desp, e.fecha_pedido) + interval '3.67 days')
    END                           AS fecha_entrega_real,
    e.direccion_envio_id,
    e.fecha_pedido
FROM elegible e
LEFT JOIN hitos h ON h.pedido_id = e.pedido_id
LEFT JOIN peso  pe ON pe.pedido_id = e.pedido_id;

CREATE UNIQUE INDEX ON f5_env(id);
CREATE INDEX ON f5_env(pedido_id);

-- Promesa de entrega: la media medida es 3,36 días sobre el despacho.
ALTER TABLE f5_env ADD COLUMN fecha_entrega_estimada date,
                   ADD COLUMN numero text, ADD COLUMN guia text,
                   ADD COLUMN lote int, ADD COLUMN direccion text;
UPDATE f5_env f SET
    fecha_entrega_estimada = (f.fecha_despacho + ((2 + floor(pg_temp.u('pr', f.n) * 4)) || ' days')::interval)::date,
    numero = 'EN-'   || to_char(f.fecha_despacho AT TIME ZONE 'America/Guayaquil', 'YYYYMMDD')
                     || '-' || lpad((5000000 + f.n)::text, 7, '0'),
    guia   = 'GUIA-' || to_char(f.fecha_despacho AT TIME ZONE 'America/Guayaquil', 'YYYYMMDD')
                     || '-' || lpad((5000000 + f.n)::text, 7, '0'),
    lote   = ((f.n - 1) / 250000)::int + 1;

UPDATE f5_env f SET direccion = COALESCE(
    (SELECT left(d.calle_principal || ', ' || ci.nombre, 400)
       FROM direccion d JOIN ciudad ci ON ci.id = d.ciudad_id
      WHERE d.id = f.direccion_envio_id), 'Direccion no registrada');

\echo '--- 1. Plan de envios construido ---'
SELECT count(*) AS envios_a_cargar, count(DISTINCT lote) AS lotes,
       min(fecha_despacho)::date AS primer_despacho,
       max(fecha_despacho)::date AS ultimo_despacho
FROM f5_env;

-- ════════════════════════════════════════════════════════════════════════════
-- 2. GUARDIAS ANTES DE ESCRIBIR
-- ════════════════════════════════════════════════════════════════════════════
DO $guardias$
DECLARE v int; v_txt text;
BEGIN
    -- (1) Ninguna fecha por delante de su pedido, y los hitos en orden.
    SELECT count(*) INTO v FROM f5_env
    WHERE fecha_despacho < fecha_pedido
       OR (fecha_entrega_real IS NOT NULL AND fecha_entrega_real < fecha_despacho);
    IF v > 0 THEN
        RAISE EXCEPTION 'ABORTA: % envios con fechas incoherentes con su pedido.', v;
    END IF;

    -- (2) Ningun envio de un pedido cancelado o no despachable.
    SELECT count(*) INTO v FROM f5_env f JOIN pedido p ON p.id = f.pedido_id
    JOIN estado_pedido ep ON ep.id = p.estado_pedido_id
    WHERE p.canal = 'tienda'
       OR ep.codigo NOT IN ('entregado','despachado','no_entregado','devuelto');
    IF v > 0 THEN RAISE EXCEPTION 'ABORTA: % envios de pedidos no elegibles.', v; END IF;

    -- (3) El costo tiene que ser el del pedido, sin excepcion.
    SELECT count(*) INTO v FROM f5_env f JOIN pedido p ON p.id = f.pedido_id
    WHERE f.costo <> p.costo_envio;
    IF v > 0 THEN RAISE EXCEPTION 'ABORTA: % envios con costo distinto al del pedido.', v; END IF;

    -- (4) NUMEROS DE DOCUMENTO: se comparan, no se razonan. La Fase 3 aprendio
    --     que el numero lleva la fecha y sobresale de la ventana del bloque.
    SELECT count(*), left(string_agg(DISTINCT n, ', '), 120) INTO v, v_txt
    FROM (SELECT e.numero AS n FROM envio e
          JOIN (SELECT DISTINCT numero FROM f5_env) g ON g.numero = e.numero) z;
    IF v > 0 THEN
        RAISE EXCEPTION 'ABORTA: % numeros de envio CHOCAN con los existentes (%).', v, v_txt;
    END IF;

    RAISE NOTICE 'Guardias OK: fechas coherentes, elegibilidad, costo y 0 choques de numero.';
END
$guardias$;

-- ════════════════════════════════════════════════════════════════════════════
-- 3. CARGA POR LOTES DE 250.000 ENVIOS
-- ════════════════════════════════════════════════════════════════════════════
CREATE OR REPLACE PROCEDURE pg_temp.cargar()
LANGUAGE plpgsql AS $carga$
DECLARE v_lote int; v_tot int; v_ini timestamptz; v_n bigint;
BEGIN
SELECT max(lote) INTO v_tot FROM f5_env;
FOR v_lote IN 1..v_tot LOOP

    v_ini := clock_timestamp();
    INSERT INTO envio (id, numero, pedido_id, transportista_id, metodo_envio_id, bodega_id,
                       direccion_entrega, numero_guia, estado, costo, peso_total_kg,
                       fecha_despacho, fecha_entrega_estimada, fecha_entrega_real,
                       fecha_creacion, despachado_por)
    OVERRIDING SYSTEM VALUE
    SELECT f.id, f.numero, f.pedido_id, f.transportista_id, f.metodo_envio_id, 4,
           f.direccion, f.guia, f.estado, f.costo, f.peso_total_kg,
           f.fecha_despacho, f.fecha_entrega_estimada, f.fecha_entrega_real,
           f.fecha_despacho, 10
    FROM f5_env f WHERE f.lote = v_lote
    ON CONFLICT (id) DO NOTHING;
    GET DIAGNOSTICS v_n = ROW_COUNT; CALL pg_temp.medir('envio', v_lote, v_ini, v_n);

    -- Seguimiento: el rastro que el cliente ve. Medido 2,99 eventos por envio.
    v_ini := clock_timestamp();
    INSERT INTO seguimiento_envio (id, envio_id, estado, descripcion, ubicacion,
                                   fecha_evento, fecha_creacion)
    OVERRIDING SYSTEM VALUE
    SELECT 2400000000 + (f.n - 1) * 3 + x.k, f.id, x.estado, x.descripcion, x.ubicacion,
           x.ts, x.ts
    FROM f5_env f
    CROSS JOIN LATERAL (VALUES
        (1, 'despachado',  'Paquete despachado desde bodega', 'Quevedo, Los Rios',
            f.fecha_despacho),
        (2, 'en_transito', 'En ruta hacia el destino',        'En transito',
            f.fecha_despacho + interval '8 hours'),
        (3, CASE f.estado WHEN 'entregado' THEN 'entregado'
                          WHEN 'devuelto'  THEN 'devuelto' END,
            CASE f.estado WHEN 'entregado' THEN 'Entregado al destinatario'
                          WHEN 'devuelto'  THEN 'Devuelto al almacen tras intento fallido' END,
            'Destino',
            CASE f.estado WHEN 'entregado' THEN f.fecha_entrega_real
                          WHEN 'devuelto'  THEN f.fecha_despacho + interval '5 days' END)
    ) x(k, estado, descripcion, ubicacion, ts)
    WHERE f.lote = v_lote AND x.estado IS NOT NULL AND x.ts IS NOT NULL
    ON CONFLICT (id) DO NOTHING;
    GET DIAGNOSTICS v_n = ROW_COUNT; CALL pg_temp.medir('seguimiento_envio', v_lote, v_ini, v_n);

    -- Novedad: solo en el camino que la justifica — el pedido no se entrego y
    -- el envio volvio al almacen. Es el flujo documentado del script 44.
    v_ini := clock_timestamp();
    INSERT INTO novedad_envio (id, envio_id, pedido_id, tipo, descripcion, intento_numero,
                               estado, accion, registrado_por, resuelto_por,
                               fecha_registro, fecha_resolucion)
    OVERRIDING SYSTEM VALUE
    SELECT 2500000000 + f.n, f.id, f.pedido_id,
           (ARRAY['cliente_ausente','direccion_incorrecta','cliente_rechazo',
                  'zona_dificil_acceso','dano_en_transito'])
               [1 + floor(pg_temp.u('tp', f.n) * 5)::int],
           'Incidencia registrada en el intento de entrega', 1,
           'resuelta', 'devuelto_almacen', 10, 10,
           f.fecha_despacho + interval '3 days',
           f.fecha_despacho + interval '5 days'
    FROM f5_env f WHERE f.lote = v_lote AND f.estado = 'devuelto'
    ON CONFLICT (id) DO NOTHING;
    GET DIAGNOSTICS v_n = ROW_COUNT; CALL pg_temp.medir('novedad_envio', v_lote, v_ini, v_n);

    -- `envio_detalle` es VESTIGIAL en este sistema: 29 filas para 2.872 envios
    -- (1,0 %). No alimenta ninguna tabla del almacen ni ningun informe. Se
    -- reproduce su tasa medida y NO se fabrican 2,4 M de filas de un patron
    -- que el dato original no tiene.
    v_ini := clock_timestamp();
    INSERT INTO envio_detalle (id, envio_id, pedido_detalle_id, cantidad, fecha_creacion)
    OVERRIDING SYSTEM VALUE
    SELECT 2300000000 + f.n, f.id, pd.id, pd.cantidad, f.fecha_despacho
    FROM f5_env f
    JOIN LATERAL (SELECT id, cantidad FROM pedido_detalle
                   WHERE pedido_id = f.pedido_id ORDER BY id LIMIT 1) pd ON true
    WHERE f.lote = v_lote AND pg_temp.u('det', f.n) < 0.010
    ON CONFLICT (id) DO NOTHING;
    GET DIAGNOSTICS v_n = ROW_COUNT; CALL pg_temp.medir('envio_detalle', v_lote, v_ini, v_n);

    COMMIT;
    RAISE NOTICE 'Lote %/% commiteado.', v_lote, v_tot;
END LOOP;
END
$carga$;
CALL pg_temp.cargar();

\echo '--- 3. Envios cargados ---'

-- ════════════════════════════════════════════════════════════════════════════
-- 4. BITACORA
-- ════════════════════════════════════════════════════════════════════════════
BEGIN;
SELECT fn_carga_registrar('fase5','101_fase5_envios','envio', 2200000001,
       (SELECT max(id) FROM envio WHERE id>=2200000000),
       (SELECT count(*) FROM envio WHERE id>=2200000000),
       'Un envio por pedido elegible: estado despachable Y canal <> tienda.');
SELECT fn_carga_registrar('fase5','101_fase5_envios','seguimiento_envio', 2400000001,
       (SELECT max(id) FROM seguimiento_envio WHERE id>=2400000000),
       (SELECT count(*) FROM seguimiento_envio WHERE id>=2400000000), NULL);
SELECT fn_carga_registrar('fase5','101_fase5_envios','novedad_envio', 2500000001,
       (SELECT COALESCE(max(id),2500000001) FROM novedad_envio WHERE id>=2500000000),
       (SELECT count(*) FROM novedad_envio WHERE id>=2500000000),
       'Solo en el camino no_entregado -> devuelto al almacen.');
SELECT fn_carga_registrar('fase5','101_fase5_envios','envio_detalle', 2300000001,
       (SELECT COALESCE(max(id),2300000001) FROM envio_detalle WHERE id>=2300000000),
       (SELECT count(*) FROM envio_detalle WHERE id>=2300000000),
       'Tasa medida del original (1,0 %): la tabla es vestigial.');

INSERT INTO carga_fase_parametro (fase, clave, valor, nota) VALUES
 ('fase5','tramos_ids','envio 2.2e9 · detalle 2.3e9 · seguimiento 2.4e9 · novedad 2.5e9',
  'Techo real = UInt32 del almacen (4.294.967.295): fact_envio.envio_id y '
  'fact_novedad_envio son UInt32. El id mas alto queda al 56 % del techo.'),
 ('fase5','regla_elegibilidad','estado despachable Y canal <> tienda',
  'Derivada de los 4.083 originales: web 100 %, telefono 100 %, tienda 1,2 %. El '
  '«73,7 % de los entregados» no era azar: la compra en tienda se retira en tienda.'),
 ('fase5','fuente_de_fechas','historial_estado_pedido',
  'fecha_despacho y fecha_entrega_real se LEEN de los hitos que el pedido ya tiene, '
  'asi la coherencia temporal sale por construccion y no por verificacion posterior.')
ON CONFLICT (fase, clave) DO UPDATE SET valor = EXCLUDED.valor, nota = EXCLUDED.nota;
COMMIT;

\echo ''
\echo '=== MEDICIONES ============================================================='
SELECT paso, sum(filas) filas, round(sum(extract(epoch FROM (fin-inicio)))::numeric,2) seg
FROM f5_medicion GROUP BY paso ORDER BY 3 DESC;

\echo ''
SELECT (SELECT count(*) FROM envio)             AS envios_total,
       (SELECT count(*) FROM envio_detalle)     AS detalle_total,
       (SELECT count(*) FROM seguimiento_envio) AS seguimiento_total,
       (SELECT count(*) FROM novedad_envio)     AS novedades_total;
