-- ============================================================================
-- 44_novedades_envio.sql — Novedades / incidencias de envío (2026-07-18)
-- Registra lo que pasa DURANTE la entrega de un pedido despachado (cliente
-- ausente, dirección incorrecta, rechazo, zona difícil, daño en tránsito) y
-- su resolución: REPROGRAMAR (nuevo intento, máx. 3) o DEVOLVER AL ALMACÉN.
--
-- Máquina de estados (sin tocar CHECKs existentes: envio.estado ya admite
-- 'fallido' y 'devuelto' desde el script 12):
--   envio:  en_transito --novedad--> fallido --reprogramar--> en_transito
--                                    fallido --devolver-----> devuelto
--   pedido: despachado (no cambia con la novedad ni el reintento)
--           despachado --devolver al almacén--> no_entregado (estado NUEVO)
--
-- Criterio de stock/RMA: devolver al almacén NO reingresa stock — el kardex
-- solo se mueve tras inspección física de BODEGA (patrón RMA, script 38).
-- El pedido 'no_entregado' queda con su inventario descontado y mercancía
-- física en bodega; el reembolso/reingreso se gestiona por soporte
-- (ticket) + gerencia. RMA de cliente NO aplica (exige entrega).
-- Idempotente: se puede re-ejecutar sin efectos dobles.
-- ============================================================================

-- ── 1) Estado de pedido nuevo: 'no_entregado' ───────────────────────────────
INSERT INTO estado_pedido (codigo, nombre, descripcion, orden, es_final, activo)
SELECT 'no_entregado', 'No entregado',
       'Envío devuelto al almacén por incidencia de entrega; stock sin reingresar (pendiente de resolución vía soporte/bodega)',
       11, true, true
WHERE NOT EXISTS (SELECT 1 FROM estado_pedido WHERE codigo = 'no_entregado');

-- ── 2) Tabla de novedades del envío ─────────────────────────────────────────
CREATE TABLE IF NOT EXISTS novedad_envio (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    envio_id         bigint NOT NULL REFERENCES envio(id),
    pedido_id        bigint NOT NULL REFERENCES pedido(id),
    tipo             varchar(30) NOT NULL CHECK (tipo IN
                         ('cliente_ausente', 'direccion_incorrecta',
                          'cliente_rechazo', 'zona_dificil_acceso',
                          'dano_en_transito')),
    descripcion      text,
    -- Nº de intento de entrega en el que ocurrió la novedad (1 = primero)
    intento_numero   integer NOT NULL DEFAULT 1 CHECK (intento_numero >= 1),
    estado           varchar(15) NOT NULL DEFAULT 'abierta'
                         CHECK (estado IN ('abierta', 'resuelta')),
    -- Acción de resolución (NULL mientras la novedad está abierta)
    accion           varchar(20) CHECK (accion IN ('reprogramada', 'devuelto_almacen')),
    registrado_por   bigint NOT NULL REFERENCES usuario(id),  -- autor del JWT
    resuelto_por     bigint REFERENCES usuario(id),
    fecha_registro   timestamptz NOT NULL DEFAULT now(),
    fecha_resolucion timestamptz,
    -- abierta <=> sin acción; resuelta <=> con acción
    CONSTRAINT novedad_envio_coherencia CHECK ((estado = 'abierta') = (accion IS NULL))
);

CREATE INDEX IF NOT EXISTS idx_novedad_envio_envio  ON novedad_envio (envio_id);
CREATE INDEX IF NOT EXISTS idx_novedad_envio_pedido ON novedad_envio (pedido_id);

-- ── 3) Privilegios (matriz por rol; despacho registra y resuelve) ───────────
GRANT SELECT, INSERT, UPDATE, DELETE ON novedad_envio TO grp_administrador;
GRANT SELECT, INSERT, UPDATE         ON novedad_envio TO grp_despacho;
GRANT SELECT ON novedad_envio TO grp_gerente, grp_vendedor, grp_bodega,
                                 grp_analista, grp_cliente;

-- ── 4) RLS: horario del personal + cliente aislado a SUS pedidos ────────────
ALTER TABLE novedad_envio ENABLE ROW LEVEL SECURITY;

-- Mismo conjunto de grupos que pol_horario de envio/seguimiento_envio
DROP POLICY IF EXISTS pol_horario ON novedad_envio;
CREATE POLICY pol_horario ON novedad_envio FOR ALL
    TO grp_administrador, grp_gerente, grp_vendedor, grp_compras,
       grp_bodega, grp_despacho, grp_analista
    USING (esta_en_horario(fn_grupo_actual()));

DROP POLICY IF EXISTS pol_cliente_propio ON novedad_envio;
CREATE POLICY pol_cliente_propio ON novedad_envio FOR SELECT TO grp_cliente
    USING (esta_en_horario('grp_cliente') AND pedido_id IN
        (SELECT id FROM pedido WHERE cliente_id = fn_cliente_actual()));

-- Nota: no hacen falta grants nuevos sobre envio / seguimiento_envio /
-- historial_estado_pedido / log_auditoria: grp_despacho ya tiene UPDATE de
-- envio, INSERT de seguimiento e historial (scripts 12/35) e INSERT de
-- log_auditoria (script 42). El id identity no requiere grant de secuencia.
