-- ============================================================================
-- 45_devolucion_proveedor.sql — Devolución a proveedor / gestión de producto
-- defectuoso (2026-07-18). Espejo del RMA pero hacia el proveedor: agrupa los
-- ítems DEFECTUOSOS y registra cómo respondió el proveedor.
--
-- DOS ORÍGENES del ítem defectuoso (pool `item_defectuoso`):
--   1. RMA: inspección de bodega con resultado 'defectuoso' (script 38) — la
--      mercancía NUNCA reingresó al stock vendible (merma documental).
--   2. RECEPCIÓN de compra: `recepcion_detalle.cantidad_rechazada` (rechazo en
--      puerta, jamás entró a stock) o marcado POSTERIOR de unidades ya
--      recibidas (ahí SÍ sale del stock vendible con kardex
--      `salida_devolucion_proveedor`, hasta hoy sin uso — deuda saldada).
--
-- Máquina de estados de devolucion_proveedor (guardias en el backend):
--   registrada (COMPRAS agrupa ítems pendientes de UN proveedor)
--     → enviada  (COMPRAS: la mercancía sale hacia el proveedor; SIN
--                 movimiento de stock vendible: nunca estuvo o ya salió)
--     → resuelta (COMPRAS registra la respuesta del proveedor:
--                 · nota_credito → crédito SIMULADO a favor, sin stock
--                 · reposicion   → reingreso de stock APTO vía StockService
--                                  con kardex `entrada_reposicion_proveedor`)
--     → cerrada  (COMPRAS archiva el caso)
--
-- item_defectuoso.estado: pendiente → en_devolucion (agrupado) → resuelto.
-- Idempotente: se puede re-ejecutar sin efectos dobles.
-- ============================================================================

-- ── 1) Tipo de movimiento NUEVO: la reposición del proveedor entra al kardex ─
INSERT INTO tipo_movimiento (codigo, nombre, naturaleza, factor, descripcion, activo)
SELECT 'entrada_reposicion_proveedor', 'Entrada por reposición de proveedor',
       'entrada', 1,
       'Mercancía nueva que el proveedor repone al resolver una devolución a proveedor',
       true
WHERE NOT EXISTS (SELECT 1 FROM tipo_movimiento WHERE codigo = 'entrada_reposicion_proveedor');

-- ── 2) Pool de ítems defectuosos pendientes de devolución a proveedor ────────
CREATE TABLE IF NOT EXISTS item_defectuoso (
    id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto_variante_id  bigint NOT NULL REFERENCES producto_variante(id),
    bodega_id             bigint NOT NULL REFERENCES bodega(id),
    cantidad              integer NOT NULL CHECK (cantidad > 0),
    -- De dónde nació el defectuoso (referencia al documento origen)
    origen                varchar(12) NOT NULL CHECK (origen IN ('rma', 'recepcion')),
    devolucion_detalle_id bigint REFERENCES devolucion_detalle(id),
    recepcion_detalle_id  bigint REFERENCES recepcion_detalle(id),
    CONSTRAINT item_defectuoso_origen_coherente CHECK (
        (origen = 'rma'       AND devolucion_detalle_id IS NOT NULL AND recepcion_detalle_id IS NULL) OR
        (origen = 'recepcion' AND recepcion_detalle_id  IS NOT NULL AND devolucion_detalle_id IS NULL)),
    -- Proveedor de origen: rastreable de inmediato en recepción (la OC lo trae);
    -- en RMA se intenta por la última OC de la variante y si no, se asigna al
    -- gestionar (COMPRAS) — por eso admite NULL.
    proveedor_id          bigint REFERENCES proveedor(id),
    costo_unitario        numeric(12,2) CHECK (costo_unitario >= 0),
    estado                varchar(15) NOT NULL DEFAULT 'pendiente'
                              CHECK (estado IN ('pendiente', 'en_devolucion', 'resuelto')),
    nota                  text,
    registrado_por        bigint NOT NULL REFERENCES usuario(id),  -- autor del JWT
    fecha_creacion        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_item_defectuoso_estado    ON item_defectuoso (estado);
CREATE INDEX IF NOT EXISTS idx_item_defectuoso_proveedor ON item_defectuoso (proveedor_id);
CREATE INDEX IF NOT EXISTS idx_item_defectuoso_recepcion ON item_defectuoso (recepcion_detalle_id);
CREATE INDEX IF NOT EXISTS idx_item_defectuoso_rma       ON item_defectuoso (devolucion_detalle_id);

-- ── 3) Devolución a proveedor: cabecera + detalle + historial ────────────────
CREATE TABLE IF NOT EXISTS devolucion_proveedor (
    id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    numero           varchar(30) NOT NULL UNIQUE,   -- DP-AAAAMMDD-n (seq_numero_documento)
    proveedor_id     bigint NOT NULL REFERENCES proveedor(id),
    estado           varchar(15) NOT NULL DEFAULT 'registrada'
                         CHECK (estado IN ('registrada', 'enviada', 'resuelta', 'cerrada')),
    -- Respuesta del proveedor (NULL hasta 'resuelta')
    tipo_resolucion  varchar(15) CHECK (tipo_resolucion IN ('nota_credito', 'reposicion')),
    monto_credito    numeric(12,2) CHECK (monto_credito >= 0),   -- solo nota_credito (simulado)
    nota_resolucion  text,
    observacion      text,
    registrado_por   bigint NOT NULL REFERENCES usuario(id),     -- autor del JWT
    fecha_envio      timestamptz,
    fecha_resolucion timestamptz,
    fecha_creacion   timestamptz NOT NULL DEFAULT now(),
    -- resuelta/cerrada exigen resolución registrada
    CONSTRAINT devolucion_proveedor_resolucion_coherente CHECK (
        (estado IN ('resuelta', 'cerrada')) = (tipo_resolucion IS NOT NULL))
);
CREATE INDEX IF NOT EXISTS idx_devolucion_proveedor_proveedor ON devolucion_proveedor (proveedor_id);
CREATE INDEX IF NOT EXISTS idx_devolucion_proveedor_estado    ON devolucion_proveedor (estado);

CREATE TABLE IF NOT EXISTS devolucion_proveedor_detalle (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    devolucion_proveedor_id bigint NOT NULL REFERENCES devolucion_proveedor(id),
    -- UN ítem defectuoso vive en UNA sola devolución a proveedor
    item_defectuoso_id      bigint NOT NULL UNIQUE REFERENCES item_defectuoso(id),
    cantidad                integer NOT NULL CHECK (cantidad > 0),
    costo_unitario          numeric(12,2) CHECK (costo_unitario >= 0),
    fecha_creacion          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_dp_detalle_cabecera ON devolucion_proveedor_detalle (devolucion_proveedor_id);

CREATE TABLE IF NOT EXISTS historial_devolucion_proveedor (
    id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    devolucion_proveedor_id bigint NOT NULL REFERENCES devolucion_proveedor(id),
    estado                  varchar(15) NOT NULL,
    usuario_id              bigint REFERENCES usuario(id),        -- autor del JWT
    comentario              text,
    fecha_creacion          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_hist_dp_cabecera ON historial_devolucion_proveedor (devolucion_proveedor_id);

-- ── 4) Privilegios (matriz por rol) ──────────────────────────────────────────
-- BODEGA identifica el defectuoso (inspección RMA + recepción + marcado
-- posterior); COMPRAS gestiona la devolución al proveedor y asigna proveedor;
-- GERENTE supervisa (solo lectura).
GRANT SELECT, INSERT, UPDATE, DELETE ON item_defectuoso, devolucion_proveedor,
      devolucion_proveedor_detalle, historial_devolucion_proveedor TO grp_administrador;

GRANT SELECT, INSERT         ON item_defectuoso TO grp_bodega;
GRANT SELECT, INSERT, UPDATE ON item_defectuoso TO grp_compras;

GRANT SELECT, INSERT, UPDATE ON devolucion_proveedor          TO grp_compras;
GRANT SELECT, INSERT         ON devolucion_proveedor_detalle  TO grp_compras;
GRANT SELECT, INSERT         ON historial_devolucion_proveedor TO grp_compras;

GRANT SELECT ON devolucion_proveedor, devolucion_proveedor_detalle,
               historial_devolucion_proveedor TO grp_bodega, grp_gerente;
GRANT SELECT ON item_defectuoso TO grp_gerente;

-- Reposición del proveedor: COMPRAS reingresa stock apto vía StockService
-- (upsert inventario + kardex). Hasta hoy solo leía inventario (script 19).
GRANT INSERT, UPDATE ON inventario            TO grp_compras;
GRANT SELECT, INSERT ON movimiento_inventario TO grp_compras;
GRANT SELECT         ON tipo_movimiento       TO grp_compras;

-- Autores visibles en las pantallas de COMPRAS (bodega ya los tiene, script 38)
GRANT SELECT (id, nombre, apellido) ON usuario TO grp_compras;

-- BODEGA audita el marcado de defectuosos vía AuditoriaService (el script 42
-- dio INSERT a vendedor/despacho/compras; bodega quedó fuera — se completa aquí)
GRANT INSERT ON log_auditoria TO grp_bodega;

-- COMPRAS ve el documento RMA de ORIGEN del ítem defectuoso (solo número, sin
-- montos: segregación intacta). pol_horario de devolucion/devolucion_detalle
-- ya incluye a grp_compras desde el script 38.
GRANT SELECT (id, numero) ON devolucion TO grp_compras;
GRANT SELECT (id, devolucion_id) ON devolucion_detalle TO grp_compras;

-- ── 5) RLS: restricción de horario del personal (patrón scripts 38/44) ───────
ALTER TABLE item_defectuoso                ENABLE ROW LEVEL SECURITY;
ALTER TABLE devolucion_proveedor           ENABLE ROW LEVEL SECURITY;
ALTER TABLE devolucion_proveedor_detalle   ENABLE ROW LEVEL SECURITY;
ALTER TABLE historial_devolucion_proveedor ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS pol_horario ON item_defectuoso;
CREATE POLICY pol_horario ON item_defectuoso FOR ALL
    TO grp_administrador, grp_gerente, grp_vendedor, grp_compras,
       grp_bodega, grp_despacho, grp_analista
    USING (esta_en_horario(fn_grupo_actual()));

DROP POLICY IF EXISTS pol_horario ON devolucion_proveedor;
CREATE POLICY pol_horario ON devolucion_proveedor FOR ALL
    TO grp_administrador, grp_gerente, grp_vendedor, grp_compras,
       grp_bodega, grp_despacho, grp_analista
    USING (esta_en_horario(fn_grupo_actual()));

DROP POLICY IF EXISTS pol_horario ON devolucion_proveedor_detalle;
CREATE POLICY pol_horario ON devolucion_proveedor_detalle FOR ALL
    TO grp_administrador, grp_gerente, grp_vendedor, grp_compras,
       grp_bodega, grp_despacho, grp_analista
    USING (esta_en_horario(fn_grupo_actual()));

DROP POLICY IF EXISTS pol_horario ON historial_devolucion_proveedor;
CREATE POLICY pol_horario ON historial_devolucion_proveedor FOR ALL
    TO grp_administrador, grp_gerente, grp_vendedor, grp_compras,
       grp_bodega, grp_despacho, grp_analista
    USING (esta_en_horario(fn_grupo_actual()));

-- Nota: los id identity no requieren grant de secuencia (patrón script 44).
-- La numeración DP-… usa seq_numero_documento (script 43), cuyo USAGE ya
-- tienen los roles que emiten documentos; el número lo genera COMPRAS.
