-- ============================================================================
-- 48_metas_venta.sql — Metas de venta por período (2026-07-22, OTD-VEN-15)
-- Cierre de brecha del catálogo táctico (docs/tactico/CATALOGO_OBJETIVOS_
-- TACTICOS.md § 11.1): no existía ninguna tabla de metas/presupuesto contra
-- la cual comparar la venta acumulada. Única tabla NUEVA que pide el catálogo.
--
-- Diseño (convenciones de novedad_envio, script 44):
--   * Período = anio + mes (enteros). SIN validación de futuro/actual a
--     PROPÓSITO: se sembrarán 12-18 meses de datos históricos y sus metas.
--   * departamento con lista blanca CHECK ('general' = meta global de la
--     tienda; el resto espeja los departamentos del catálogo táctico).
--   * UNA meta por período y departamento (UNIQUE); editar/toggle activo es
--     la vía de corrección, no duplicar filas.
--   * Trazabilidad: fijada_por (FK usuario, SIEMPRE del JWT) + fecha_creacion
--     default + fecha_actualizacion por trigger touch (NUNCA la escribe la app).
--
-- GRANTs: fijar metas es atribución de Gerencia/Administración; VENDEDOR y
-- ANALISTA solo LEEN (consumen el informe meta vs. venta real). Bodega,
-- Despacho, Compras, Soporte y Cliente quedan FUERA: la meta es un monto
-- financiero (segregación, script 41).
-- RLS: pol_horario con los grupos con acceso (patrón script 44).
-- Idempotente y transaccional.
-- ============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS meta_venta (
    id                  bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    anio                integer NOT NULL CHECK (anio BETWEEN 2000 AND 2100),
    mes                 integer NOT NULL CHECK (mes BETWEEN 1 AND 12),
    departamento        varchar(20) NOT NULL DEFAULT 'general' CHECK (departamento IN
                            ('general', 'ventas', 'compras', 'inventario',
                             'logistica', 'soporte', 'marketing')),
    monto_meta          numeric(12,2) NOT NULL CHECK (monto_meta > 0),
    notas               text,
    fijada_por          bigint NOT NULL REFERENCES usuario(id),  -- autor del JWT
    activo              boolean NOT NULL DEFAULT true,
    fecha_creacion      timestamptz NOT NULL DEFAULT now(),
    fecha_actualizacion timestamptz,
    CONSTRAINT uq_meta_venta_periodo UNIQUE (anio, mes, departamento)
);

CREATE INDEX IF NOT EXISTS idx_meta_venta_periodo ON meta_venta (anio, mes);

-- fecha_actualizacion la mantiene el trigger touch genérico (regla de oro 1)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_trigger
                   WHERE tgname = 'trg_meta_venta_touch'
                     AND tgrelid = 'meta_venta'::regclass) THEN
        CREATE TRIGGER trg_meta_venta_touch BEFORE UPDATE ON meta_venta
            FOR EACH ROW EXECUTE FUNCTION fn_touch_fecha_actualizacion();
    END IF;
END $$;

-- ── Privilegios (GRANT re-ejecutable sin efecto doble) ──────────────────────
GRANT SELECT, INSERT, UPDATE, DELETE ON meta_venta TO grp_administrador;
GRANT SELECT, INSERT, UPDATE         ON meta_venta TO grp_gerente;
GRANT SELECT ON meta_venta TO grp_vendedor, grp_analista;
-- id es IDENTITY: la secuencia propia no exige grant aparte (patrón script 44)

-- ── RLS: horario del personal (mismos grupos que tienen acceso) ─────────────
ALTER TABLE meta_venta ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS pol_horario ON meta_venta;
CREATE POLICY pol_horario ON meta_venta FOR ALL
    TO grp_administrador, grp_gerente, grp_vendedor, grp_analista
    USING (esta_en_horario(fn_grupo_actual()));

COMMIT;
