-- ============================================================================
-- 99_revert_fase6.sql — RetailMind · reversión de la Fase 6 (la posventa)
--
--   Ensayo en seco (ejecuta, VERIFICA y deshace):
--   docker compose exec -T postgres psql -U postgres -d retailmind \
--       -v ON_ERROR_STOP=1 -v ensayo=1 -f - < retailmind/sql/postgres/99_revert_fase6.sql
--
--   En firme: lo mismo sin `-v ensayo=1`.
--
-- ---------------------------------------------------------------------------
-- POR QUÉ ESTA REVERSIÓN NO ES UN SIMPLE DELETE
-- ---------------------------------------------------------------------------
-- Las de las fases 1 a 5 sí lo eran: cargaban HOJAS del modelo y bastaba con
-- borrar por tramo de ids. Ésta no, porque la Fase 6 tocó el KARDEX, que es
-- la única estructura del sistema con ESTADO ACUMULADO: cada movimiento
-- guarda el saldo que dejó, así que borrar 77.798 entradas del pasado deja
-- obsoleto el saldo corrido de todo lo que venía después en esas 5.911
-- posiciones — 5.559.282 movimientos.
--
-- Por eso la reversión tiene cuatro pasos y no uno:
--     1. borrar la posventa (hojas, por tramo de ids);
--     2. borrar los reingresos del kardex;
--     3. RECALCULAR la cadena de las posiciones afectadas;
--     4. devolver `inventario.stock_actual` al saldo resultante.
--
-- El orden importa: si se recalculara antes de borrar, se recalcularía con
-- las entradas todavía dentro.
--
-- Tramos que se borran (ninguno solapa con nada preexistente):
--     devolucion                   >= 2.600.000.000
--     devolucion_detalle           >= 2.700.000.000
--     historial_estado_devolucion  >= 2.800.000.000
--     ticket_soporte               >= 2.900.000.000
--     resena                       >= 3.000.000.000
--     reembolso                    >= 3.100.000.000
--     movimiento_inventario        >= 3.300.000.000
--     item_defectuoso  ← por devolucion_detalle_id, NO por id propio: su
--                        columna id es GENERATED BY DEFAULT y la carga la
--                        dejó correr, así que el tramo 3.2e9 quedó SIN USAR.
--                        Se identifica por su padre, que sí está en tramo.
--
-- Lo que debe quedar EXACTAMENTE como estaba: 197 devoluciones, 275 líneas,
-- 1.010 hitos, 249 tickets, 344 reseñas, 85 reembolsos, 38 ítems defectuosos,
-- 7.930.685 movimientos de kardex y 426.722 unidades en 11.406 posiciones.
--
-- VA EN UNA SOLA TRANSACCIÓN, y eso es deliberado. La primera versión
-- reencadenaba por lotes con COMMIT, igual que la carga; pero entonces el modo
-- ensayo habría sido una MENTIRA: el ROLLBACK final solo deshace la
-- transacción abierta, y los lotes ya confirmados se habrían quedado. Una
-- reversión que no se puede ensayar de verdad no es una red de seguridad, es
-- un adorno. El precio es un WAL grande durante unos minutos; la garantía es
-- que `-v ensayo=1` deja la base EXACTAMENTE como estaba.
--
-- SE AUTOVERIFICA Y ABORTA. IDEMPOTENTE.
-- ============================================================================
\set ON_ERROR_STOP on
\timing on
\if :{?ensayo}
\else
  \set ensayo 0
\endif

-- ── Foto previa de lo que NO se debe mover ──────────────────────────────────
CREATE TEMP TABLE rev6_antes AS
SELECT 'pedido' t, count(*) n, COALESCE(round(sum(total),2),0) v FROM pedido
UNION ALL SELECT 'pedido_detalle', count(*), COALESCE(round(sum(subtotal),2),0) FROM pedido_detalle
UNION ALL SELECT 'factura_venta', count(*), COALESCE(round(sum(total),2),0) FROM factura_venta
UNION ALL SELECT 'pago', count(*), COALESCE(round(sum(monto),2),0) FROM pago
UNION ALL SELECT 'envio', count(*), COALESCE(round(sum(costo),2),0) FROM envio
UNION ALL SELECT 'devolucion ORIG', count(*), COALESCE(round(sum(monto_total),2),0)
  FROM devolucion WHERE id < 2600000000
UNION ALL SELECT 'ticket ORIG', count(*), 0 FROM ticket_soporte WHERE id < 2900000000
UNION ALL SELECT 'resena ORIG', count(*), COALESCE(sum(calificacion),0) FROM resena WHERE id < 3000000000
UNION ALL SELECT 'kardex ORIG', count(*), COALESCE(sum(cantidad),0)
  FROM movimiento_inventario WHERE id < 3300000000
UNION ALL SELECT 'grupo_horario', count(*), 0 FROM grupo_horario;

-- ── Las posiciones que habrá que recalcular, ANTES de borrar sus entradas ───
CREATE TEMP TABLE rev6_pos AS
SELECT DISTINCT producto_variante_id v, bodega_id b
FROM movimiento_inventario WHERE id >= 3300000000;
CREATE UNIQUE INDEX ON rev6_pos (v, b);
ANALYZE rev6_pos;

BEGIN;

-- ════════════════════════════════════════════════════════════════════════════
-- PASO 1 y 2 · borrado. Al revés de las dependencias.
-- ════════════════════════════════════════════════════════════════════════════

-- ÍNDICE TRANSITORIO, y la razón por la que existe.
-- `devolucion.ticket_soporte_id` es una FK **sin índice**, y su regla es
-- ON DELETE SET NULL: al borrar un ticket, PostgreSQL busca quién lo
-- referencia... recorriendo `devolucion` ENTERA. Con los 249 tickets sembrados
-- eso no se nota; con los 179.602 de la década son 179.602 recorridos de una
-- tabla de 145.734 filas — medido en el primer ensayo: 163.384.365 tuplas
-- leídas y 27 minutos sin terminar el DELETE.
-- El índice se crea aquí y se destruye al acabar: no toca el esquema de
-- negocio, vive lo que dura la reversión. Es PARCIAL porque solo 3 de las 197
-- devoluciones originales tienen ticket asociado.
CREATE INDEX IF NOT EXISTS rev6_tmp_dev_ticket
    ON devolucion (ticket_soporte_id) WHERE ticket_soporte_id IS NOT NULL;

-- item_defectuoso cuelga de devolucion_detalle SIN cascada: se va primero.
DELETE FROM item_defectuoso WHERE devolucion_detalle_id >= 2700000000;
DELETE FROM reembolso                   WHERE id >= 3100000000;
DELETE FROM historial_estado_devolucion WHERE id >= 2800000000;
DELETE FROM devolucion_detalle          WHERE id >= 2700000000;
-- `devolucion.ticket_soporte_id` apunta a ticket con ON DELETE SET NULL, así
-- que el orden entre estas dos no es crítico, pero se respeta el del modelo.
DELETE FROM devolucion                  WHERE id >= 2600000000;
DELETE FROM ticket_soporte              WHERE id >= 2900000000;
DELETE FROM resena                      WHERE id >= 3000000000;

-- El kardex, que es lo que obliga a los pasos 3 y 4.
DELETE FROM movimiento_inventario       WHERE id >= 3300000000;

DELETE FROM carga_fase_registro  WHERE fase = 'fase6';
DELETE FROM carga_fase_parametro WHERE fase = 'fase6';

-- ════════════════════════════════════════════════════════════════════════════
-- PASO 3 · reencadenar las posiciones tocadas, en UN solo enunciado.
--   No se parchea el saldo guardado: se reconstruye la suma corrida desde el
--   origen de cada cadena, leyendo por (fecha_creacion, id).
-- ════════════════════════════════════════════════════════════════════════════
WITH calc AS (
    SELECT mi.id,
           mi.cantidad * tm.factor AS delta,
           sum(mi.cantidad * tm.factor) OVER (
               PARTITION BY mi.producto_variante_id, mi.bodega_id
               ORDER BY mi.fecha_creacion, mi.id
               ROWS UNBOUNDED PRECEDING) AS nuevo
    FROM movimiento_inventario mi
    JOIN tipo_movimiento tm ON tm.id = mi.tipo_movimiento_id
    JOIN rev6_pos p ON p.v = mi.producto_variante_id AND p.b = mi.bodega_id
)
UPDATE movimiento_inventario m
   SET stock_anterior = c.nuevo - c.delta,
       stock_nuevo    = c.nuevo
FROM calc c
WHERE m.id = c.id
  AND (m.stock_nuevo    IS DISTINCT FROM c.nuevo
    OR m.stock_anterior IS DISTINCT FROM c.nuevo - c.delta);

-- ════════════════════════════════════════════════════════════════════════════
-- PASO 4 · el saldo, y la autoverificación completa.
-- ════════════════════════════════════════════════════════════════════════════

UPDATE inventario i SET stock_actual = k.saldo
FROM (SELECT mi.producto_variante_id v, mi.bodega_id b,
             sum(mi.cantidad * tm.factor) saldo
      FROM movimiento_inventario mi
      JOIN tipo_movimiento tm ON tm.id = mi.tipo_movimiento_id
      JOIN rev6_pos p ON p.v = mi.producto_variante_id AND p.b = mi.bodega_id
      GROUP BY 1, 2) k
WHERE i.producto_variante_id = k.v AND i.bodega_id = k.b
  AND i.stock_actual IS DISTINCT FROM k.saldo;

DO $verif$
DECLARE
    n bigint; restos text := ''; d text;
    v_pos bigint; v_cuad bigint; v_rotos bigint;
BEGIN
    -- (a) Cero residuos de la fase.
    SELECT count(*) INTO n FROM devolucion WHERE id >= 2600000000;
    IF n > 0 THEN restos := restos || format('  devolucion: %s%s', n, E'\n'); END IF;
    SELECT count(*) INTO n FROM devolucion_detalle WHERE id >= 2700000000;
    IF n > 0 THEN restos := restos || format('  devolucion_detalle: %s%s', n, E'\n'); END IF;
    SELECT count(*) INTO n FROM historial_estado_devolucion WHERE id >= 2800000000;
    IF n > 0 THEN restos := restos || format('  historial: %s%s', n, E'\n'); END IF;
    SELECT count(*) INTO n FROM ticket_soporte WHERE id >= 2900000000;
    IF n > 0 THEN restos := restos || format('  ticket: %s%s', n, E'\n'); END IF;
    SELECT count(*) INTO n FROM resena WHERE id >= 3000000000;
    IF n > 0 THEN restos := restos || format('  resena: %s%s', n, E'\n'); END IF;
    SELECT count(*) INTO n FROM reembolso WHERE id >= 3100000000;
    IF n > 0 THEN restos := restos || format('  reembolso: %s%s', n, E'\n'); END IF;
    SELECT count(*) INTO n FROM item_defectuoso WHERE devolucion_detalle_id >= 2700000000;
    IF n > 0 THEN restos := restos || format('  item_defectuoso: %s%s', n, E'\n'); END IF;
    SELECT count(*) INTO n FROM movimiento_inventario WHERE id >= 3300000000;
    IF n > 0 THEN restos := restos || format('  kardex: %s%s', n, E'\n'); END IF;
    IF restos <> '' THEN
        RAISE EXCEPTION 'ABORTA: quedan filas de la Fase 6 sin borrar:%', E'\n' || restos;
    END IF;

    -- (b) Lo preexistente, intacto al centavo.
    SELECT string_agg(format('  %s: %s/%s -> %s/%s', a.t, a.n, a.v, b.n, b.v), E'\n') INTO d
    FROM rev6_antes a
    JOIN (SELECT 'pedido' t, count(*) n, COALESCE(round(sum(total),2),0) v FROM pedido
          UNION ALL SELECT 'pedido_detalle', count(*), COALESCE(round(sum(subtotal),2),0) FROM pedido_detalle
          UNION ALL SELECT 'factura_venta', count(*), COALESCE(round(sum(total),2),0) FROM factura_venta
          UNION ALL SELECT 'pago', count(*), COALESCE(round(sum(monto),2),0) FROM pago
          UNION ALL SELECT 'envio', count(*), COALESCE(round(sum(costo),2),0) FROM envio
          UNION ALL SELECT 'devolucion ORIG', count(*), COALESCE(round(sum(monto_total),2),0)
            FROM devolucion WHERE id < 2600000000
          UNION ALL SELECT 'ticket ORIG', count(*), 0 FROM ticket_soporte WHERE id < 2900000000
          UNION ALL SELECT 'resena ORIG', count(*), COALESCE(sum(calificacion),0) FROM resena WHERE id < 3000000000
          UNION ALL SELECT 'kardex ORIG', count(*), COALESCE(sum(cantidad),0)
            FROM movimiento_inventario WHERE id < 3300000000
          UNION ALL SELECT 'grupo_horario', count(*), 0 FROM grupo_horario) b ON b.t = a.t
    WHERE a.n <> b.n OR a.v <> b.v;
    IF d IS NOT NULL THEN
        RAISE EXCEPTION 'ABORTA: la reversion movio datos que no debia:%', E'\n' || d;
    END IF;

    -- (c) El kardex, cuadrado y sin enlaces rotos. Es lo que esta reversión
    --     tiene que demostrar y las de las fases anteriores no necesitaban.
    SELECT count(*), count(*) FILTER (WHERE i.stock_actual = COALESCE(k.saldo, 0))
      INTO v_pos, v_cuad
    FROM inventario i
    LEFT JOIN (SELECT mi.producto_variante_id v, mi.bodega_id b,
                      sum(mi.cantidad * tm.factor) saldo
               FROM movimiento_inventario mi
               JOIN tipo_movimiento tm ON tm.id = mi.tipo_movimiento_id
               GROUP BY 1, 2) k ON k.v = i.producto_variante_id AND k.b = i.bodega_id;
    IF v_pos <> v_cuad THEN
        RAISE EXCEPTION 'ABORTA: kardex descuadrado (% de % posiciones).', v_cuad, v_pos;
    END IF;

    SELECT count(*) INTO v_rotos FROM (
        SELECT mi.stock_anterior,
               lag(mi.stock_nuevo) OVER (PARTITION BY mi.producto_variante_id, mi.bodega_id
                                         ORDER BY mi.fecha_creacion, mi.id) prev
        FROM movimiento_inventario mi
        JOIN rev6_pos p ON p.v = mi.producto_variante_id AND p.b = mi.bodega_id) x
    WHERE (prev IS NULL AND stock_anterior <> 0) OR (prev IS NOT NULL AND stock_anterior <> prev);
    IF v_rotos > 0 THEN
        RAISE EXCEPTION 'ABORTA: % enlaces rotos tras reencadenar.', v_rotos;
    END IF;

    RAISE NOTICE 'Reversion verificada: 0 residuos, % de % posiciones cuadradas, '
                 '0 enlaces rotos, y lo preexistente intacto al centavo.',
                 v_cuad, v_pos;
END
$verif$;

-- El andamio se retira: el índice era para la reversión, no para el esquema.
DROP INDEX IF EXISTS rev6_tmp_dev_ticket;

\if :ensayo
ROLLBACK;
\echo ''
\echo 'ENSAYO EN SECO: la reversion se ejecuto ENTERA -borrado, reencadenado,'
\echo 'saldo y verificacion-, y se deshizo. La base queda como estaba.'
\else
COMMIT;
\echo ''
\echo 'FASE 6 REVERTIDA.'
\endif


\echo ''
SELECT (SELECT count(*) FROM devolucion) devoluciones, (SELECT count(*) FROM ticket_soporte) tickets,
       (SELECT count(*) FROM resena) resenas, (SELECT count(*) FROM movimiento_inventario) kardex,
       (SELECT sum(stock_actual) FROM inventario) unidades;
